import 'package:brick_offline_first_with_supabase/brick_offline_first_with_supabase.dart';
import 'package:brick_sqlite/brick_sqlite.dart';
import 'package:brick_sqlite/memory_cache_provider.dart';
import 'package:brick_supabase/brick_supabase.dart' hide Supabase;
import 'package:sqflite_common/sqlite_api.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

// Generated by build_runner — run `dart run build_runner build`
import 'brick.g.dart';
import 'db/schema.g.dart';

/// Singleton repository providing offline-first data access.
///
/// Writes go to local SQLite first (instant UI feedback).
/// Brick queues and syncs to Supabase when online.
class Repository extends OfflineFirstWithSupabaseRepository {
  static Repository? _instance;

  Repository._({
    required super.supabaseProvider,
    required super.sqliteProvider,
    required super.migrations,
    required super.offlineRequestQueue,
    super.memoryCacheProvider,
  });

  factory Repository() => _instance!;

  /// Call once from main.dart before runApp.
  static Future<Repository> configure(DatabaseFactory databaseFactory) async {
    final (client, queue) =
        OfflineFirstWithSupabaseRepository.clientQueue(
      databaseFactory: databaseFactory,
      // Don't queue auth, storage, or function requests
      ignorePaths: {'/auth/v1', '/storage/v1', '/functions/v1'},
    );

    final supabaseClient = Supabase.instance.client;

    final provider = SupabaseProvider(
      supabaseClient,
      modelDictionary: supabaseModelDictionary,
    );

    _instance = Repository._(
      supabaseProvider: provider,
      sqliteProvider: SqliteProvider(
        'carp_network.sqlite',
        databaseFactory: databaseFactory,
        modelDictionary: sqliteModelDictionary,
      ),
      migrations: migrations,
      offlineRequestQueue: queue,
      memoryCacheProvider: MemoryCacheProvider(),
    );

    await _instance!.initialize();
    return _instance!;
  }
}
